### ISSUE TITLE
create-db.bat 创建数据库 报错，求解脱！

### ISSUE THREAD

**Issue by waylau** [zhangkaitao/es#62]
[INFO] create db.
[INFO] please confirm db encoding utf-8.
[INFO] please confirm has modified es/web/pom.xml-->profile-->development--->con
nection.admin.url/connection.username/password
[INFO] Scanning for projects...
Downloading: http://maven.oschina.net/content/groups/public/org/apache/maven/plu
gins/maven-war-plugin/2.3/maven-war-plugin-2.3.jar
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/maven/plug
ins/maven-war-plugin/2.3/maven-war-plugin-2.3.jar (82 KB at 11.0 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/maven/plu
gins/maven-site-plugin/3.0/maven-site-plugin-3.0.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/maven/plug
ins/maven-site-plugin/3.0/maven-site-plugin-3.0.pom (20 KB at 1.9 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/maven/plu
gins/maven-plugins/21/maven-plugins-21.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/maven/plug
ins/maven-plugins/21/maven-plugins-21.pom (13 KB at 10.0 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/maven/mav
en-parent/20/maven-parent-20.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/maven/mave
n-parent/20/maven-parent-20.pom (25 KB at 14.8 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/maven/plu
gins/maven-site-plugin/3.0/maven-site-plugin-3.0.jar
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/maven/plug
ins/maven-site-plugin/3.0/maven-site-plugin-3.0.jar (112 KB at 36.9 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/je
tty-maven-plugin/8.1.8.v20121106/jetty-maven-plugin-8.1.8.v20121106.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/jet
ty-maven-plugin/8.1.8.v20121106/jetty-maven-plugin-8.1.8.v20121106.pom (7 KB at
0.9 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/je
tty-integration-project/8.1.8.v20121106/jetty-integration-project-8.1.8.v2012110
6.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/jet
ty-integration-project/8.1.8.v20121106/jetty-integration-project-8.1.8.v20121106
.pom (12 KB at 4.3 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/je
tty-parent/13/jetty-parent-13.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/jet
ty-parent/13/jetty-parent-13.pom (4 KB at 4.9 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/eclipse/jetty/je
tty-parent/19/jetty-parent-19.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/eclipse/jetty/jet
ty-parent/19/jetty-parent-19.pom (20 KB at 17.4 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/je
tty-maven-plugin/8.1.8.v20121106/jetty-maven-plugin-8.1.8.v20121106.jar
Downloaded: http://maven.oschina.net/content/groups/public/org/mortbay/jetty/jet
ty-maven-plugin/8.1.8.v20121106/jetty-maven-plugin-8.1.8.v20121106.jar (72 KB at
 41.9 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/tomcat/ma
ven/tomcat7-maven-plugin/2.2/tomcat7-maven-plugin-2.2.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/tomcat/mav
en/tomcat7-maven-plugin/2.2/tomcat7-maven-plugin-2.2.pom (12 KB at 2.4 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/tomcat/ma
ven/tomcat-maven-plugin/2.2/tomcat-maven-plugin-2.2.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/tomcat/mav
en/tomcat-maven-plugin/2.2/tomcat-maven-plugin-2.2.pom (33 KB at 16.4 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/apache/12
/apache-12.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/apache/12/
apache-12.pom (16 KB at 19.9 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/apache/tomcat/ma
ven/tomcat7-maven-plugin/2.2/tomcat7-maven-plugin-2.2.jar
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/tomcat/mav
en/tomcat7-maven-plugin/2.2/tomcat7-maven-plugin-2.2.jar (112 KB at 35.9 KB/sec)

Downloading: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/na
tive2ascii-maven-plugin/1.0-alpha-1/native2ascii-maven-plugin-1.0-alpha-1.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/nat
ive2ascii-maven-plugin/1.0-alpha-1/native2ascii-maven-plugin-1.0-alpha-1.pom (3
KB at 3.2 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/mo
jo/13/mojo-13.pom
Downloaded: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/moj
o/13/mojo-13.pom (9 KB at 8.9 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/na
tive2ascii-maven-plugin/1.0-alpha-1/native2ascii-maven-plugin-1.0-alpha-1.jar
Downloaded: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/nat
ive2ascii-maven-plugin/1.0-alpha-1/native2ascii-maven-plugin-1.0-alpha-1.jar (5
KB at 5.4 KB/sec)
Downloading: http://maven.oschina.net/content/groups/public/com/googlecode/maven
-db-plugin/1.4/maven-db-plugin-1.4.pom
Downloading: http://repo1.maven.org/maven2/com/googlecode/maven-db-plugin/1.4/ma
ven-db-plugin-1.4.pom
Downloading: http://repository.codehaus.org/com/googlecode/maven-db-plugin/1.4/m
aven-db-plugin-1.4.pom
Downloading: https://maven-db-plugin.googlecode.com/svn/maven/repo/com/googlecod
e/maven-db-plugin/1.4/maven-db-plugin-1.4.pom
Downloading: http://repo.maven.apache.org/maven2/com/googlecode/maven-db-plugin/
1.4/maven-db-plugin-1.4.pom
[WARNING] Failed to retrieve plugin descriptor for com.googlecode:maven-db-plugi
n:1.4: Plugin com.googlecode:maven-db-plugin:1.4 or one of its dependencies coul
d not be resolved: Failed to read artifact descriptor for com.googlecode:maven-d
b-plugin:jar:1.4
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metada
ta.xml
Downloading: https://maven-db-plugin.googlecode.com/svn/maven/repo/org/apache/ma
ven/plugins/maven-metadata.xml
Downloading: http://maven.oschina.net/content/groups/public/org/apache/maven/plu
gins/maven-metadata.xml
Downloading: http://repository.codehaus.org/org/apache/maven/plugins/maven-metad
ata.xml
Downloading: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/ma
ven-metadata.xml
Downloaded: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadat
a.xml (13 KB at 17.1 KB/sec)
Downloading: http://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded: http://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml (
20 KB at 28.9 KB/sec)
Downloading: http://repository.codehaus.org/org/codehaus/mojo/maven-metadata.xml

Downloading: https://maven-db-plugin.googlecode.com/svn/maven/repo/org/codehaus/
mojo/maven-metadata.xml
Downloaded: http://maven.oschina.net/content/groups/public/org/apache/maven/plug
ins/maven-metadata.xml (15 KB at 3.6 KB/sec)
Downloaded: http://maven.oschina.net/content/groups/public/org/codehaus/mojo/mav
en-metadata.xml (25 KB at 6.3 KB/sec)
[WARNING] Could not transfer metadata org.apache.maven.plugins/maven-metadata.xm
l from/to maven-db-plugin-repo (https://maven-db-plugin.googlecode.com/svn/maven
/repo): Connect to maven-db-plugin.googlecode.com:443 [maven-db-plugin.googlecod
e.com/74.125.23.82] failed: Connection timed out: connect
[WARNING] Could not transfer metadata org.codehaus.mojo/maven-metadata.xml from/
to maven-db-plugin-repo (https://maven-db-plugin.googlecode.com/svn/maven/repo):
 Connect to maven-db-plugin.googlecode.com:443 [maven-db-plugin.googlecode.com/7
4.125.23.82] failed: Connection timed out: connect
[WARNING] Failure to transfer org.apache.maven.plugins/maven-metadata.xml from h
ttps://maven-db-plugin.googlecode.com/svn/maven/repo was cached in the local rep
ository, resolution will not be reattempted until the update interval of maven-d
b-plugin-repo has elapsed or updates are forced. Original error: Could not trans
fer metadata org.apache.maven.plugins/maven-metadata.xml from/to maven-db-plugin
-repo (https://maven-db-plugin.googlecode.com/svn/maven/repo): Connect to maven-
db-plugin.googlecode.com:443 [maven-db-plugin.googlecode.com/74.125.23.82] faile
d: Connection timed out: connect
[WARNING] Failure to transfer org.codehaus.mojo/maven-metadata.xml from https://
maven-db-plugin.googlecode.com/svn/maven/repo was cached in the local repository
, resolution will not be reattempted until the update interval of maven-db-plugi
n-repo has elapsed or updates are forced. Original error: Could not transfer met
adata org.codehaus.mojo/maven-metadata.xml from/to maven-db-plugin-repo (https:/
/maven-db-plugin.googlecode.com/svn/maven/repo): Connect to maven-db-plugin.goog
lecode.com:443 [maven-db-plugin.googlecode.com/74.125.23.82] failed: Connection
timed out: connect
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadat
a.xml
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-
metadata.xml
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-m
etadata.xml (13 KB at 20.3 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata
.xml (20 KB at 24.4 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:39 min
[INFO] Finished at: 2014-07-18T09:57:12+08:00
[INFO] Final Memory: 8M/19M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'db' in the current project and in the plugin
 groups [org.apache.maven.plugins, org.codehaus.mojo] available from the reposit
ories [local (D:\workspaceMaven), oschina Releases (http://maven.oschina.net/con
tent/groups/public), maven2-repo (http://repo1.maven.org/maven2/), Codehaus repo
sitory (http://repository.codehaus.org/), maven-db-plugin-repo (https://maven-db
-plugin.googlecode.com/svn/maven/repo), central (http://repo.maven.apache.org/ma
ven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundF
orPrefixException
请按任意键继续. . .

**Comment by longfeizheng** [comment]
我也遇到了 也找吧maven-db-plugin放到本地仓库了 咋还是不行？
